/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamCodeRouteImport } from './routes/team.$code'
import { Route as LobbyCodeRouteImport } from './routes/lobby.$code'
import { Route as BattleCodeRouteImport } from './routes/battle.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamCodeRoute = TeamCodeRouteImport.update({
  id: '/team/$code',
  path: '/team/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyCodeRoute = LobbyCodeRouteImport.update({
  id: '/lobby/$code',
  path: '/lobby/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const BattleCodeRoute = BattleCodeRouteImport.update({
  id: '/battle/$code',
  path: '/battle/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/battle/$code': typeof BattleCodeRoute
  '/lobby/$code': typeof LobbyCodeRoute
  '/team/$code': typeof TeamCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/battle/$code': typeof BattleCodeRoute
  '/lobby/$code': typeof LobbyCodeRoute
  '/team/$code': typeof TeamCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/battle/$code': typeof BattleCodeRoute
  '/lobby/$code': typeof LobbyCodeRoute
  '/team/$code': typeof TeamCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/battle/$code' | '/lobby/$code' | '/team/$code'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/battle/$code' | '/lobby/$code' | '/team/$code'
  id: '__root__' | '/' | '/battle/$code' | '/lobby/$code' | '/team/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BattleCodeRoute: typeof BattleCodeRoute
  LobbyCodeRoute: typeof LobbyCodeRoute
  TeamCodeRoute: typeof TeamCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$code': {
      id: '/team/$code'
      path: '/team/$code'
      fullPath: '/team/$code'
      preLoaderRoute: typeof TeamCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby/$code': {
      id: '/lobby/$code'
      path: '/lobby/$code'
      fullPath: '/lobby/$code'
      preLoaderRoute: typeof LobbyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battle/$code': {
      id: '/battle/$code'
      path: '/battle/$code'
      fullPath: '/battle/$code'
      preLoaderRoute: typeof BattleCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BattleCodeRoute: BattleCodeRoute,
  LobbyCodeRoute: LobbyCodeRoute,
  TeamCodeRoute: TeamCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
